//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kon.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string LoginTime { get; set; }
        public string LogoutTime { get; set; }
        public string TimeSpentOnSystem { get; set; }
        public string UnsuccessfulLogoutReason { get; set; }
        public int IdAthorization { get; set; }
    
        public virtual Authorization Authorization { get; set; }
    }
}
